version: '3'
services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: mysql
    env_file: ./mysql/mysql.env
    environment:
      - TZ=Asia/Tokyo
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:
